const BASE_URL='https://www.jobs.ac.uk/search/';
const USER_AGENT='JobMatchPortal/1.0 (+https://github.com/mittalraghav45/jobmatchportal)';
const DEFAULT_PAGE_SIZE=25,MAX_PAGE_SIZE=100;
export const JOBS_AC_UK_DISCIPLINES=[
 {label:'Computer Sciences',value:'computer-sciences',facet:'academic',subdisciplines:[{label:'Artificial Intelligence',value:'artificial-intelligence'},{label:'Computer Science',value:'computer-science'},{label:'Cyber Security',value:'cyber-security'},{label:'Information Systems',value:'information-systems'},{label:'Software Engineering',value:'software-engineering'}]},
 {label:'IT Services',value:'it-services',facet:'nonAcademic',subdisciplines:[]},
 {label:'Web Design & Development',value:'web-design-and-development',facet:'nonAcademic',subdisciplines:[]},
 {label:'Engineering & Technology',value:'engineering-and-technology',facet:'academic',subdisciplines:[{label:'Electrical & Electronic Engineering',value:'electrical-and-electronic-engineering'},{label:'Other Engineering',value:'other-engineering'}]}
];
const LOCATION_COORDS={belfast:'54.597285,-5.93012',southampton:'50.9097,-1.4044',london:'51.5074,-0.1278',manchester:'53.4808,-2.2426',birmingham:'52.4862,-1.8904',bristol:'51.4545,-2.5879',leeds:'53.8008,-1.5491',liverpool:'53.4084,-2.9916',edinburgh:'55.9533,-3.1883',glasgow:'55.8642,-4.2518',cardiff:'51.4816,-3.1791',newcastle:'54.9783,-1.6178',nottingham:'52.9548,-1.1581',oxford:'51.7520,-1.2577',cambridge:'52.2053,0.1218',sheffield:'53.3811,-1.4701',coventry:'52.4068,-1.5197',reading:'51.4543,-0.9781',york:'53.9591,-1.0815'};
function decodeHtml(v=''){return String(v).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,c)=>String.fromCharCode(Number(c))).replace(/&#x([0-9a-f]+);/gi,(_,c)=>String.fromCharCode(parseInt(c,16)))}
const BLOCK='(?:article|aside|div|dl|dt|dd|li|main|p|section|tr|ul|ol|h[1-6])';
function htmlToText(v=''){return decodeHtml(String(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(new RegExp(`<${BLOCK}\\b[^>]*>`,'gi'),'\n').replace(new RegExp(`</${BLOCK}>`,'gi'),'\n').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,' '))}
function clean(v=''){return htmlToText(v).replace(/\s+/g,' ').trim()}
function lines(v=''){return htmlToText(v).split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)}
function abs(v){try{return new URL(v,BASE_URL).href}catch{return ''}}
function jobUrl(v){return /(?:^|\.)jobs\.ac\.uk\/(?:job|vacancy)\//i.test(v)}
function fields(fragment,title){const a=lines(fragment),i=a.findIndex(x=>x===title),w=i>=0?a.slice(i+1):a,li=w.findIndex(x=>/^location\s*:/i.test(x)),si=w.findIndex(x=>/^salary\s*:/i.test(x)),pi=w.findIndex(x=>/^(?:date placed|placed on)\s*:/i.test(x)),ci=w.findIndex(x=>/^(?:closes|closing date|expires)\s*:?/i.test(x)),end=[li,si,pi,ci].filter(x=>x>=0).sort((x,y)=>x-y)[0]??w.length,meta=w.slice(0,end).filter(x=>!/^save$|^apply$/i.test(x));let company=meta.at(-1)||'',department=meta.length>1?meta.at(-2)||'':'';if(company.includes(' - ')){const p=company.split(' - ');company=p.shift().trim();department=p.join(' - ').trim()||department}return{companyName:company,department,location:li>=0?w[li].replace(/^location\s*:\s*/i,'').trim():'',salary:si>=0?w[si].replace(/^salary\s*:\s*/i,'').trim():'',posted:pi>=0?w[pi].replace(/^(?:date placed|placed on)\s*:\s*/i,'').trim():'',closing:ci>=0?w[ci].replace(/^(?:closes|closing date|expires)\s*:?\s*/i,'').trim():''}}
export function parseJobsAcUkHtml(html=''){const found=[],seen=new Set(),p=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=p.exec(html))){const url=abs(m[1]);if(!jobUrl(url)||seen.has(url))continue;const title=clean(m[2]);if(!title||title.length>300)continue;found.push({url,title,start:m.index,end:p.lastIndex});seen.add(url)}return found.map((x,i)=>{const fragment=html.slice(x.end,found[i+1]?.start??Math.min(html.length,x.end+8000)),f=fields(fragment,x.title);return{id:`jobs-ac-uk-${Buffer.from(x.url).toString('base64url').slice(0,32)}`,externalId:x.url,title:x.title,companyName:f.companyName,department:f.department,location:f.location||'UK',description:'',url:x.url,posting_date:f.posted||null,closing_date:f.closing||null,salary:f.salary||'',ats:'jobs-ac-uk',source_verified:true,source:'jobs.ac.uk'}})}
export function buildJobsAcUkSearchUrl({keywords='',location='',discipline='computer-sciences',subDiscipline='',page=1,pageSize=DEFAULT_PAGE_SIZE}={}){const size=Math.min(MAX_PAGE_SIZE,Math.max(1,parseInt(pageSize,10)||DEFAULT_PAGE_SIZE)),pg=Math.max(1,parseInt(page,10)||1),p=new URLSearchParams();if(keywords.trim())p.set('keywords',keywords.trim());const s=JOBS_AC_UK_DISCIPLINES.find(x=>x.value===discipline)||JOBS_AC_UK_DISCIPLINES[0];p.append(s.facet==='nonAcademic'?'nonAcademicDisciplineFacet[0]':'academicDisciplineFacet[0]',s.value);if(s.facet==='academic'&&subDiscipline)p.append('subDisciplineFacet[0]',subDiscipline);const loc=location.trim();if(loc){p.set('location',loc);const c=LOCATION_COORDS[loc.toLowerCase()];if(c){p.set('locality[0]',loc);p.set('locationCoords[0]',c);p.set('distance','30')}}p.set('pageSize',String(size));p.set('sortOrder','1');p.set('startIndex',String((pg-1)*size+1));return `${BASE_URL}?${p.toString()}`}
export async function searchJobsAcUk({keywords='',location='',discipline='computer-sciences',subDiscipline='',page=1,pageSize=DEFAULT_PAGE_SIZE,timeoutMs=15000}={}){const url=buildJobsAcUkSearchUrl({keywords,location,discipline,subDiscipline,page,pageSize}),c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':USER_AGENT,Accept:'text/html,application/xhtml+xml'}});if(!r.ok)throw Error(`jobs.ac.uk returned HTTP ${r.status}`);const html=await r.text(),jobs=parseJobsAcUkHtml(html),m=clean(html).match(/([\d,]+)\s+Jobs? Found/i);return{source:'jobs.ac.uk',searchUrl:url,keywords:keywords.trim(),location:location.trim(),discipline,subDiscipline,page:Math.max(1,parseInt(page,10)||1),pageSize:Math.min(MAX_PAGE_SIZE,Math.max(1,parseInt(pageSize,10)||DEFAULT_PAGE_SIZE)),totalFound:m?Number(m[1].replace(/,/g,'')):null,jobs}}finally{clearTimeout(t)}}
