import React,{useEffect,useMemo,useState,useRef}from'react';
import './product-dashboard.css';
import './job-filter-panel.css';
import './my-matches.css';
import ApplicationReview from './ApplicationReview.jsx';
import JobSearchPanel from './JobSearchPanel.jsx';
import MyMatches from './MyMatches.jsx';

const configuredApiBase=String(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');
const browserHost=typeof window!=='undefined'?window.location.hostname:'';
const isLocalBrowser=browserHost==='localhost'||browserHost==='127.0.0.1'||browserHost==='::1';
const API=configuredApiBase&&(!/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(configuredApiBase)||isLocalBrowser)?configuredApiBase:'';
const EMPTY_PROFILE={profileId:'default',name:'Candidate',skills:[]};
async function api(path,options={}){const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function displayText(value,fallback=''){if(value===null||value===undefined)return fallback;if(typeof value==='string'||typeof value==='number')return String(value);if(Array.isArray(value))return value.map(v=>displayText(v,'')).filter(Boolean).join(', ');if(typeof value==='object'){if(value.name)return displayText(value.name,fallback);if(value.label)return displayText(value.label,fallback);if(value.ats)return displayText(value.ats,fallback);if(value.url)return displayText(value.url,fallback);return fallback}return fallback}
function job(x){const source=x.source;const sourceLabel=displayText(source,displayText(x.sourceName,''));const sourceUrl=typeof source==='object'&&source?displayText(source.url,''):'';const rawSkills=Array.isArray(x.skills)?x.skills:Array.isArray(x.technicalSkills)?x.technicalSkills:[];const skills=rawSkills.map(s=>displayText(s,'')).filter(Boolean);return{...x,id:x.id||x._id||x.externalId||x.canonicalUrl,title:displayText(x.title||x.jobTitle,'Untitled role'),companyName:displayText(x.companyName||x.company?.name,'Company being resolved'),location:displayText(x.location,'Location not specified'),skills,sponsorship:x.sponsorship&&typeof x.sponsorship==='object'?x.sponsorship:{status:displayText(x.sponsorship||x.sponsorshipStatus||x.company?.sponsorship,'unknown')},employerType:displayText(x.employerType||x.company?.employerType,'private'),nation:displayText(x.nation,''),applyUrl:displayText(x.applyUrl||x.url||sourceUrl,''),employerMetadata:x.company?.metadata||x.companyMetadata||{},source:sourceLabel}}
const STATUSES=['saved','tailoring','ready_to_apply','applied','interview','offer','rejected','withdrawn'];
const STATUS_LABELS={saved:'Saved',tailoring:'Tailoring',ready_to_apply:'Ready to apply',applied:'Applied',interview:'Interview',offer:'Offer',rejected:'Rejected',withdrawn:'Withdrawn'};

export default function ProductDashboard(){
const[v,setV]=useState('dashboard'),[theme,setTheme]=useState(()=>localStorage.getItem('jobmatch-theme')||'dark'),[jobs,setJobs]=useState([]),[jobTotal,setJobTotal]=useState(0),[jobPage,setJobPage]=useState(1),[jobLoading,setJobLoading]=useState(false),[apps,setApps]=useState([]),[companies,setCompanies]=useState([]),[companyTotal,setCompanyTotal]=useState(0),[profile,setProfile]=useState(EMPTY_PROFILE),[city,setCity]=useState(''),[category,setCategory]=useState('all'),[verifiedLive,setVerifiedLive]=useState(true),[q,setQ]=useState(''),[jobSource,setJobSource]=useState('mongo'),[jobsAcUkLocation,setJobsAcUkLocation]=useState(''),[jobsAcUkDiscipline,setJobsAcUkDiscipline]=useState('computer-sciences'),[jobsAcUkSubDiscipline,setJobsAcUkSubDiscipline]=useState(''),[sponsorship,setSponsorship]=useState('all'),[nations,setNations]=useState([]),[employerTypes,setEmployerTypes]=useState([]),[workMode,setWorkMode]=useState('all'),[employmentType,setEmploymentType]=useState(''),[sort,setSort]=useState('recent'),[appFilter,setAppFilter]=useState('all'),[appQuery,setAppQuery]=useState(''),[companyQ,setCompanyQ]=useState(''),[companyPage,setCompanyPage]=useState(1),[jobSel,setJobSel]=useState(null),[match,setMatch]=useState(null),[appSel,setAppSel]=useState(null),[busy,setBusy]=useState(false),[companyBusy,setCompanyBusy]=useState(false),[error,setError]=useState('');
const JOB_LIMIT=50;
const jobRequest=useRef(0);
useEffect(()=>{document.documentElement.classList.toggle('light-theme',theme==='light');localStorage.setItem('jobmatch-theme',theme)},[theme]);
const loadCompanyCount=async()=>{try{const d=await api('/api/companies/count');setCompanyTotal(Number(d.total)||0)}catch(e){setError(e.message)}};
const loadCompanies=async(page=1,query=companyQ)=>{setCompanyBusy(true);try{const p=new URLSearchParams({limit:'50',page:String(page)});if(query.trim())p.set('q',query.trim());const d=await api(`/api/companies?${p}`);setCompanies(Array.isArray(d)?d:d.companies||[]);setCompanyTotal(d.total||0);setCompanyPage(d.page||page)}catch(e){setError(e.message)}finally{setCompanyBusy(false)}};
const loadJobs=async(page=jobPage)=>{const request=++jobRequest.current;setJobLoading(true);try{setError('');if(jobSource==='jobs-ac-uk'){const p=new URLSearchParams({page:String(page),pageSize:String(JOB_LIMIT),discipline:jobsAcUkDiscipline});if(jobsAcUkSubDiscipline)p.set('subDiscipline',jobsAcUkSubDiscipline);if(q.trim())p.set('q',q.trim());if(jobsAcUkLocation.trim())p.set('location',jobsAcUkLocation.trim());const d=await api(`/api/jobs-ac-uk?${p}`);if(request!==jobRequest.current)return;const jl=Array.isArray(d?.jobs)?d.jobs:[];setJobs(jl.map(job));setJobTotal(Number(d?.totalFound)||jl.length);setJobPage(Number(d?.page)||page);return}const p=new URLSearchParams({limit:String(JOB_LIMIT),page:String(page),sort});if(city.trim())p.set('city',city.trim());if(category!=='all')p.set('category',category);p.set('verifiedLive',String(verifiedLive));if(q.trim())p.set('q',q.trim());if(sponsorship!=='all')p.set('sponsorship',sponsorship);if(nations.length)p.set('nation',nations.join(','));if(employerTypes.length)p.set('employerType',employerTypes.join(','));if(workMode!=='all')p.set('workMode',workMode);if(employmentType)p.set('employmentType',employmentType);const d=await api(`/api/jobs?${p}`);if(request!==jobRequest.current)return;const jl=Array.isArray(d)?d:d.jobs||d.data||[];setJobs(jl.map(job));setJobTotal(Number(d?.pagination?.total??jl.length));setJobPage(Number(d?.pagination?.page)||page)}catch(e){if(request!==jobRequest.current)return;setError(`Unable to load jobs: ${e.message}. Use Refresh to retry.`);setJobs([]);setJobTotal(0)}finally{if(request===jobRequest.current)setJobLoading(false)}};
const loadApps=async()=>{try{const a=await api('/api/applications?limit=100');const al=Array.isArray(a)?a:a.applications||a.data||[];setApps(al)}catch(e){setError(e.message)}};
const load=async()=>{await Promise.all([loadJobs(1),loadApps(),loadCompanyCount()]);try{const p=await api('/api/profile/default');setProfile(p.profile||p)}catch{}};
useEffect(()=>{loadJobs(1)},[category,verifiedLive,jobSource,jobsAcUkLocation,jobsAcUkDiscipline,jobsAcUkSubDiscipline,sponsorship,nations.join(','),employerTypes.join(','),workMode,employmentType,sort]);
useEffect(()=>{const timer=setTimeout(()=>loadJobs(1),350);return()=>clearTimeout(timer)},[q,city]);
useEffect(()=>{if(v==='dashboard')loadJobs(1)},[v]);
useEffect(()=>{loadApps();loadCompanyCount();api('/api/profile/default').then(p=>setProfile(p.profile||p)).catch(e=>setError(e.message))},[]);
const filtered=jobs;
const filteredApps=useMemo(()=>apps.filter(a=>{const ok=appFilter==='all'||a.status===appFilter;const t=`${a.jobTitle||a.job?.title||''} ${a.companyName||a.job?.company||''}`.toLowerCase();return ok&&t.includes(appQuery.toLowerCase())}),[apps,appFilter,appQuery]);
const counts=useMemo(()=>STATUSES.reduce((a,s)=>(a[s]=apps.filter(x=>x.status===s).length,a),{all:apps.length}),[apps]);
const analyse=async j=>{setJobSel(j);setMatch(null);setBusy(true);try{const d=await api('/api/match',{method:'POST',body:JSON.stringify({jobId:j.id,profileId:profile.profileId||profile.id||'default',job:j,profile})});setMatch(d.match||d)}catch(e){setError(`Unable to match job: ${e.message}`)}finally{setBusy(false)}};
const prepare=async j=>{try{const d=await api(`/api/match/jobs/${encodeURIComponent(j.id)}/application`,{method:'POST',body:JSON.stringify({profileId:profile.profileId||profile.id||'default'})});const a=d.application||d;setApps(x=>[a,...x.filter(x=>(x.applicationId||x._id||x.id)!==(a.applicationId||a._id||a.id))]);setAppSel(a);setJobSel(null);setV('applications')}catch(e){if(e?.message==='Application already exists for this job'){await loadApps();setV('applications');return}setError(e.message)}};
const openApp=async a=>{setAppSel(a);try{const id=a.applicationId||a._id||a.id,d=await api(`/api/applications/${id}`);setAppSel(d.application||d)}catch(e){setError(e.message)}};
const generate=async()=>{if(!appSel)return;setBusy(true);try{const id=appSel.applicationId||appSel._id||appSel.id,d=await api(`/api/applications/${id}/generate-pack`,{method:'POST',body:JSON.stringify({profileId:profile.profileId||profile.id||'default'})}),a=d.application||d;setAppSel(a);setApps(x=>x.map(v=>(v.applicationId||v._id||v.id)===id?a:v))}catch(e){setError(e.message)}finally{setBusy(false)}};
const status=async s=>{if(!appSel)return;setBusy(true);try{const id=appSel.applicationId||appSel._id||appSel.id,d=await api(`/api/applications/${id}/status`,{method:'PATCH',body:JSON.stringify({status:s})}),a=d.application||d;setAppSel(a);setApps(x=>x.map(v=>(v.applicationId||v._id||v.id)===id?a:v))}catch(e){setError(e.message)}finally{setBusy(false)}};
const title=v==='dashboard'?'Dashboard':v==='matches'?'My Matches':v==='jobs'?'Jobs':v==='sponsors'?'Sponsor companies':v==='applications'?'Applications':'Candidate profile';
const clearFilters=()=>{setCity('');setCategory('all');setVerifiedLive(true);setQ('');setJobsAcUkLocation('');setJobsAcUkDiscipline('computer-sciences');setJobsAcUkSubDiscipline('');setJobSource('mongo');setNations([]);setEmployerTypes([]);setSponsorship('all');setWorkMode('all');setEmploymentType('');setSort('recent');setJobPage(1)};
return <div className="portal"><aside className="sidebar"><div className="brand"><span className="brand-mark">J</span><h2>JobMatch</h2></div>{[['dashboard','Dashboard'],['matches','My Matches'],['jobs','Jobs'],['sponsors','Sponsors'],['applications','Applications'],['profile','Candidate profile']].map(([k,l])=><button className={v===k?'nav active':'nav'} onClick={()=>{setV(k);if(k==='sponsors'&&!companies.length)loadCompanies(1,companyQ)}} key={k}>{k==='applications'&&counts.all>0?`${l} (${counts.all})`:l}</button>)}<div className="sidebar-footer">UK software engineering intelligence</div></aside><main className="main"><header><div><h1>{title}</h1><p>UK software engineering job intelligence · sponsorship-aware matching</p></div><div className="header-actions"><button className="theme-toggle" onClick={()=>setTheme(x=>x==='dark'?'light':'dark')}>{theme==='dark'?'☀️ Light':'🌙 Dark'}</button><button onClick={load}>Refresh</button></div></header>{error&&<div className="notice">{error}</div>}
{v==='dashboard'&&<><div className="stats"><Card label="UK jobs" value={jobTotal}/><Card label="Applications" value={counts.all}/><Card label="Sponsor companies" value={companyTotal.toLocaleString()}/></div><section><div className="section-head"><div><h2>Recent matches</h2><p>UK technology roles ready for matching against your profile.</p></div><button className="secondary" onClick={()=>setV('matches')}>View My Matches</button></div><JobList jobs={filtered.slice(0,8)} analyse={analyse}/></section></>}
{v==='matches'&&<MyMatches profileId={profile.profileId||profile.id||'default'} onPrepare={prepare}/>}
{v==='jobs'&&<section><div className="section-head"><div><h2>{jobSource==='jobs-ac-uk'?'jobs.ac.uk search':'UK job market'}</h2><p>{jobSource==='jobs-ac-uk'?'Search jobs.ac.uk directly; results retain their original source links.':'Server-side search and filters — the browser only loads one page at a time.'}</p></div><span className="sponsor verified">{jobSource==='jobs-ac-uk'?'jobs.ac.uk':'UK technology'}</span></div><JobSearchPanel city={city} setCity={setCity} category={category} setCategory={setCategory} verifiedLive={verifiedLive} setVerifiedLive={setVerifiedLive} source={jobSource} setSource={setJobSource} jobsAcUkLocation={jobsAcUkLocation} setJobsAcUkLocation={setJobsAcUkLocation} jobsAcUkDiscipline={jobsAcUkDiscipline} setJobsAcUkDiscipline={setJobsAcUkDiscipline} jobsAcUkSubDiscipline={jobsAcUkSubDiscipline} setJobsAcUkSubDiscipline={setJobsAcUkSubDiscipline} q={q} setQ={setQ} nations={nations} setNations={setNations} employerTypes={employerTypes} setEmployerTypes={setEmployerTypes} sponsorship={sponsorship} setSponsorship={setSponsorship} workMode={workMode} setWorkMode={setWorkMode} employmentType={employmentType} setEmploymentType={setEmploymentType} sort={sort} setSort={setSort} onClear={clearFilters} jobTotal={jobTotal} page={jobPage} limit={JOB_LIMIT} onPageChange={p=>loadJobs(p)} loading={jobLoading}/><JobList jobs={filtered} analyse={analyse} loading={jobLoading}/></section>}
{v==='sponsors'&&<section><div className="section-head"><div><h2>Golden sponsor dataset</h2><p>{companyTotal.toLocaleString()} sponsor-company records available from MongoDB.</p></div><span className="sponsor verified">MongoDB</span></div><form onSubmit={e=>{e.preventDefault();loadCompanies(1,companyQ)}} className="toolbar"><input className="input" value={companyQ} onChange={e=>setCompanyQ(e.target.value)} placeholder="Search sponsor companies"/><button type="submit">Search</button></form>{companyBusy?<p className="muted">Loading sponsor companies…</p>:companies.length?companies.map(c=><article className="job" key={c._id||c.companyId}><div><small>{c.metadata?.industry||'Company'} · {c.metadata?.location||'UK'}</small><h3>{c.companyName}</h3><p>{c.companyNumber||'No company number'}</p></div><div className="job-actions"><span className="sponsor">{c.sponsorship||'unknown'}</span>{c.careersUrl&&<a href={c.careersUrl} target="_blank" rel="noreferrer"><button type="button">Careers</button></a>}</div></article>):<p>No sponsor companies found.</p>}<div className="pagination"><button disabled={companyPage<=1||companyBusy} onClick={()=>loadCompanies(companyPage-1,companyQ)}>Previous</button><span>Page {companyPage} · {companyTotal.toLocaleString()} companies</span><button disabled={companyPage*50>=companyTotal||companyBusy} onClick={()=>loadCompanies(companyPage+1,companyQ)}>Next</button></div></section>}
{v==='applications'&&<section><div className="section-head"><div><h2>Application pipeline</h2><p>Track every role from saved through offer.</p></div></div><div className="application-stats">{[['all','All applications'],...STATUSES.map(s=>[s,STATUS_LABELS[s]])].map(([s,l])=><button key={s} className={appFilter===s?'app-stat active':'app-stat'} onClick={()=>setAppFilter(s)}><span>{l}</span><strong>{s==='all'?counts.all:counts[s]}</strong></button>)}</div><div className="toolbar"><input className="input" value={appQuery} onChange={e=>setAppQuery(e.target.value)} placeholder="Search applications by company or role"/><select value={appFilter} onChange={e=>setAppFilter(e.target.value)}><option value="all">All statuses</option>{STATUSES.map(s=><option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select></div>{filteredApps.length?<div className="application-list">{filteredApps.map((a,i)=><article className="job application-card" key={a.applicationId||a._id||a.id||i}><div><small>{a.companyName||a.job?.company||'Company'}</small><h3>{a.jobTitle||a.job?.title||'Application'}</h3></div><div className="job-actions"><span className={`sponsor status-${a.status||'saved'}`}>{STATUS_LABELS[a.status]||a.status||'Saved'}</span><button onClick={()=>openApp(a)}>Review</button></div></article>)}</div>:<div className="empty-state"><h3>No applications here yet</h3><p>Prepare an application from a matched UK role and it will appear here.</p><button className="primary" onClick={()=>setV('matches')}>Find matches</button></div>}</section>}
{v==='profile'&&<section><h2>Candidate profile</h2><p className="muted">This profile powers the matching engine.</p><div className="profile"><b>Name</b><span>{profile.name||'Candidate'}</span><b>Skills</b><span>{(profile.skills||[]).join(' · ')}</span><b>Target</b><span>UK software engineering</span></div></section>}
</main>{jobSel&&<MatchModal job={jobSel} match={match} busy={busy} onClose={()=>setJobSel(null)} onPrepare={()=>prepare(jobSel)}/>} {appSel&&<ApplicationReview application={appSel} busy={busy} onClose={()=>setAppSel(null)} onGenerate={generate} onStatus={status}/>}</div>}
function Card({label,value}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}
function JobList({jobs,analyse,loading}){if(loading&&!jobs.length)return <div className="empty-state"><h3>Searching the job index…</h3><p>Applying your filters on the server.</p></div>;if(!jobs.length)return <div className="empty-state"><h3>No jobs to display</h3><p>Try other filters or refresh if the request failed.</p></div>;return <div>{jobs.map(x=><article className="job" key={x.id||x._id}><div><small>{displayText(x.companyName,'Employer not resolved')} · {displayText(x.source||x.nation,'UK-wide')} · {displayText(x.employerType,'private')}</small><h3>{displayText(x.title,'Untitled role')}</h3><p>{displayText(x.location,'Location not specified')}</p><div>{(Array.isArray(x.skills)?x.skills:[]).slice(0,5).map(s=><span className="tag" key={s}>{displayText(s,'')}</span>)}</div></div><div className="job-actions"><span className="sponsor">{x.verification?.status==='live'&&x.status?.isLive?'Verified live':x.verification?.status==='closed'?'Closed':'Unverified'}</span><span className={`sponsor ${x.sponsorship?.status==='verified'?'verified':''}`}>{displayText(x.sponsorship?.status||x.sponsorship,'unknown')}</span>{displayText(x.applyUrl,'')&&<a href={displayText(x.applyUrl,'')} target="_blank" rel="noreferrer"><button type="button">Apply</button></a>}<button onClick={()=>analyse(x)}>View match</button></div></article>)}</div>}
function MatchModal({job,match,busy,onClose,onPrepare}){return <div className="modal-backdrop" onClick={onClose}><div className="match-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><small>{displayText(job.companyName)}</small><h2>{displayText(job.title,'Untitled role')}</h2><p>{displayText(job.location,'Location not specified')} · {displayText(job.nation,'UK-wide')}</p><div className="match-score"><strong>{match?.score??'—'}%</strong><span>match</span></div>{busy&&<p className="muted">Checking backend matching engine…</p>}<div className="match-grid"><div><h3>Matched skills</h3>{(match?.matchedSkills||[]).map(x=><span className="tag positive" key={x}>{displayText(x,'')}</span>)}</div><div><h3>Missing / unmatched</h3>{(match?.missingSkills||[]).map(x=><span className="tag" key={x}>{displayText(x,'')}</span>)}</div></div><div className="evidence"><b>Sponsorship</b><span>{displayText(job.sponsorship?.status||job.sponsorship,'unknown')}</span></div><p className="muted">An employer licence does not confirm sponsorship for this vacancy. Unknown evidence is not a refusal.</p><div className="job-actions">{displayText(job.applyUrl,'')&&<a href={displayText(job.applyUrl,'')} target="_blank" rel="noreferrer"><button type="button">Open application</button></a>}<button className="primary" disabled={busy||!match} onClick={onPrepare}>Prepare application</button></div></div></div>}
