import React,{useEffect,useMemo,useState}from'react';
import './product-dashboard.css';
import ApplicationReview from './ApplicationReview.jsx';
const API=(import.meta.env.VITE_API_BASE_URL||'http://localhost:3001').replace(/\/$/,'');
const DEMO_PROFILE={id:'default',name:'Candidate',skills:['React','TypeScript','JavaScript','Node.js','AWS']};
const DEMO=[{id:'demo-1',title:'Software Engineer',companyName:'Monzo',location:'London, UK',skills:['React','TypeScript','Node.js'],sponsorship:{status:'verified'}},{id:'demo-2',title:'Frontend Engineer',companyName:'Deliveroo',location:'London, UK',skills:['React','TypeScript'],sponsorship:{status:'unknown'}},{id:'demo-3',title:'Software Developer',companyName:'Wise',location:'London, UK',skills:['JavaScript','React','Node.js'],sponsorship:{status:'unknown'}}];
async function api(path,options={}){const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function job(x){return{...x,id:x.id||x._id||x.externalId||x.canonicalUrl,title:x.title||x.jobTitle||'Untitled role',companyName:x.companyName||x.company?.name||'Unknown company',location:x.location||'Location not specified',skills:x.skills||x.technicalSkills||[],sponsorship:x.sponsorship||{status:x.sponsorshipStatus||'unknown'}}}
function localMatch(j,p){const w=new Set((p?.skills||[]).map(x=>String(x).toLowerCase())),s=(j.skills||[]).map(String),m=s.filter(x=>w.has(x.toLowerCase())),n=s.filter(x=>!w.has(x.toLowerCase()));return{score:Math.min((s.length?Math.round(m.length/s.length*80):0)+(j.sponsorship?.status==='verified'?20:10),100),matchedSkills:m,missingSkills:n}}
export default function ProductDashboard(){const[v,setV]=useState('dashboard'),[jobs,setJobs]=useState([]),[apps,setApps]=useState([]),[profile,setProfile]=useState(DEMO_PROFILE),[q,setQ]=useState(''),[jobSel,setJobSel]=useState(null),[match,setMatch]=useState(null),[appSel,setAppSel]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
const load=async()=>{try{setError('');const[j,a]=await Promise.all([api('/api/jobs?limit=50'),api('/api/applications?limit=50')]);const jl=Array.isArray(j)?j:j.jobs||j.data||[],al=Array.isArray(a)?a:a.applications||a.data||[];setJobs(jl.map(job));setApps(al);try{const p=await api('/api/profile/default');setProfile(p.profile||p)}catch{}}catch(e){setError(e.message);setJobs(DEMO);setApps([]);setProfile(DEMO_PROFILE)}};
useEffect(()=>{load()},[]);const filtered=useMemo(()=>jobs.filter(x=>`${x.title} ${x.companyName} ${x.location} ${(x.skills||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase())),[jobs,q]);
const analyse=async j=>{setJobSel(j);setMatch(localMatch(j,profile));setBusy(true);try{const d=await api('/api/match',{method:'POST',body:JSON.stringify({jobId:j.id,profileId:profile.id||'default',job:j,profile})});setMatch(d.match||d)}catch{}finally{setBusy(false)}};
const prepare=async j=>{try{const d=await api('/api/applications',{method:'POST',body:JSON.stringify({jobId:j.id,profileId:profile.id||'default',status:'saved'})});const a=d.application||d;setApps(x=>[a,...x]);setAppSel(a);setJobSel(null);setV('applications')}catch(e){setError(e.message)}};
const openApp=async a=>{setAppSel(a);try{const d=await api(`/api/applications/${a._id||a.id}`);setAppSel(d.application||d)}catch{}};
const generate=async()=>{if(!appSel)return;setBusy(true);try{const id=appSel._id||appSel.id,d=await api(`/api/applications/${id}/generate-pack`,{method:'POST',body:JSON.stringify({})}),a=d.application||d;setAppSel(a);setApps(x=>x.map(v=>(v._id||v.id)===id?a:v))}catch(e){setError(e.message)}finally{setBusy(false)}};
const status=async s=>{if(!appSel)return;setBusy(true);try{const id=appSel._id||appSel.id,d=await api(`/api/applications/${id}/status`,{method:'PATCH',body:JSON.stringify({status:s})}),a=d.application||d;setAppSel(a);setApps(x=>x.map(v=>(v._id||v.id)===id?a:v))}catch(e){setError(e.message)}finally{setBusy(false)}};
return <div className="portal"><aside className="sidebar"><h2>JobMatch</h2>{[['dashboard','Dashboard'],['jobs','Jobs'],['applications','Applications'],['profile','Candidate profile']].map(([k,l])=><button className={v===k?'nav active':'nav'} onClick={()=>setV(k)} key={k}>{l}</button>)}</aside><main className="main"><header><div><h1>{v==='dashboard'?'Dashboard':v==='jobs'?'Jobs':v==='applications'?'Applications':'Candidate profile'}</h1><p>UK software engineering job intelligence</p></div><button onClick={load}>Refresh</button></header>{error&&<div className="notice">{error}</div>}{v==='dashboard'&&<><div className="stats"><Card label="Jobs" value={jobs.length}/><Card label="Applications" value={apps.length}/><Card label="Interviews" value={apps.filter(x=>x.status==='interview').length}/></div><section><div className="section-head"><div><h2>Recent matches</h2><p>Open a role to inspect its match and evidence.</p></div><button onClick={()=>setV('jobs')}>View all</button></div><JobList jobs={filtered.slice(0,8)} analyse={analyse}/></section></>}{v==='jobs'&&<section><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search jobs, companies, skills or locations"/><h2>{filtered.length} jobs</h2><JobList jobs={filtered} analyse={analyse}/></section>}{v==='applications'&&<section><h2>Application pipeline</h2>{apps.length?apps.map((a,i)=><article className="job" key={a._id||a.id||i}><div><small>{a.companyName||a.job?.companyName||'Company'}</small><h3>{a.jobTitle||a.job?.title||'Application'}</h3><p>Application status: {a.status||'saved'}</p></div><div><span className="sponsor">{a.status||'saved'}</span><button onClick={()=>openApp(a)}>Review application</button></div></article>):<p>No applications yet.</p>}</section>}{v==='profile'&&<section><h2>Candidate profile</h2><div className="profile"><b>Name</b><span>{profile.name||'Candidate'}</span><b>Skills</b><span>{(profile.skills||[]).join(' · ')}</span><b>Target</b><span>UK software engineering</span></div></section>}</main>{jobSel&&<MatchModal job={jobSel} match={match} busy={busy} onClose={()=>setJobSel(null)} onPrepare={()=>prepare(jobSel)}/>} {appSel&&<ApplicationReview application={appSel} busy={busy} onClose={()=>setAppSel(null)} onGenerate={generate} onStatus={status}/>}</div>}
function Card({label,value}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}
function JobList({jobs,analyse}){return <div>{jobs.map(x=><article className="job" key={x.id||x._id}><div><small>{x.companyName}</small><h3>{x.title}</h3><p>{x.location}</p><div>{(x.skills||[]).slice(0,5).map(s=><span className="tag" key={s}>{s}</span>)}</div></div><div><span className="sponsor">{x.sponsorship?.status||'unknown'}</span><button onClick={()=>analyse(x)}>View match</button></div></article>)}</div>}
function MatchModal({job,match,busy,onClose,onPrepare}){return <div className="modal-backdrop" onClick={onClose}><div className="match-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><small>{job.companyName}</small><h2>{job.title}</h2><p>{job.location}</p><div className="match-score"><strong>{match?.score??'—'}%</strong><span>match</span></div>{busy&&<p className="muted">Checking backend matching engine…</p>}<div className="match-grid"><div><h3>Matched skills</h3>{(match?.matchedSkills||[]).map(x=><span className="tag positive" key={x}>{x}</span>)}</div><div><h3>Missing / unmatched</h3>{(match?.missingSkills||[]).map(x=><span className="tag" key={x}>{x}</span>)}</div></div><div className="evidence"><b>Sponsorship</b><span>{job.sponsorship?.status||'unknown'}</span></div><p className="muted">Unknown sponsorship evidence is not treated as a negative sponsorship claim.</p><button className="primary" onClick={onPrepare}>Prepare application</button></div></div>}
